"""Capture, stitch and paginate: the rendering pipeline behind webpage2pdf."""

import base64
import io
import sys
import time

from PIL import Image, ImageDraw, ImageFont
from selenium import webdriver

# Stitched screenshots of long pages easily exceed Pillow's decompression-bomb
# guard; the images here are self-generated by Chrome, not untrusted input.
Image.MAX_IMAGE_PIXELS = None
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait

# Page sizes in millimetres (width, height)
PAGE_SIZES = {
    "a4": (210, 297),
    "letter": (216, 279),
    "legal": (216, 356),
}

# Reference width all layout metrics are designed against; actual metrics are
# scaled proportionally so any --width/--scale combination keeps the same look.
_REF_WIDTH = 2800

# Fonts are tried in order; the CJK-capable ones come first so non-Latin page
# titles don't render as tofu boxes.
_FONT_CANDIDATES = [
    # macOS
    "/System/Library/Fonts/PingFang.ttc",
    "/System/Library/Fonts/Hiragino Sans GB.ttc",
    "/System/Library/Fonts/HelveticaNeue.ttc",
    "/System/Library/Fonts/Helvetica.ttc",
    # Linux
    "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc",
    "/usr/share/fonts/truetype/noto/NotoSansCJK-Regular.ttc",
    "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    # Windows
    "C:/Windows/Fonts/msyh.ttc",
    "C:/Windows/Fonts/arial.ttf",
]

_CHUNK_HEIGHT = 4000  # CSS px per screenshot; keeps each capture well under CDP texture limits


def log(msg):
    print(msg, flush=True)


def launch_browser(width=1400, headless=True, chrome_binary=None, user_data_dir=None):
    options = Options()
    if chrome_binary:
        options.binary_location = chrome_binary
    if headless:
        options.add_argument("--headless=new")
    if user_data_dir:
        options.add_argument(f"--user-data-dir={user_data_dir}")
    options.add_argument(f"--window-size={width},1000")
    options.add_argument("--hide-scrollbars")
    driver = webdriver.Chrome(options=options)
    driver.set_page_load_timeout(90)
    return driver


def wait_for_page(driver, extra_wait=3.0):
    try:
        WebDriverWait(driver, 30).until(
            lambda d: d.execute_script("return document.readyState") == "complete"
        )
    except Exception:
        log("  warning: page did not fully load within 30s, exporting as-is")
    if extra_wait > 0:
        time.sleep(extra_wait)


def trigger_lazy_load(driver, step=800, pause=0.25, max_steps=200):
    """Scroll through the page so lazy-loaded images and infinite content render."""
    y = 0
    for _ in range(max_steps):
        height = driver.execute_script(
            "return Math.max(document.body.scrollHeight, document.documentElement.scrollHeight)"
        )
        if y >= height:
            break
        driver.execute_script(f"window.scrollTo(0, {y})")
        time.sleep(pause)
        y += step
    driver.execute_script("window.scrollTo(0, 0)")
    time.sleep(0.5)


def capture_full_page(driver, width, scale):
    """Screenshot the whole page in chunks via CDP and stitch into one image."""
    full_height = driver.execute_script(
        "return Math.max(document.body.scrollHeight, document.documentElement.scrollHeight)"
    )
    if not full_height:
        raise RuntimeError(
            "Page height is 0, nothing to capture (the page may have failed to load)"
        )
    log(f"  page height: {full_height}px")

    screenshots = []
    for y_start in range(0, full_height, _CHUNK_HEIGHT):
        chunk_h = min(_CHUNK_HEIGHT, full_height - y_start)
        driver.execute_cdp_cmd("Emulation.setDeviceMetricsOverride", {
            "width": width, "height": chunk_h, "deviceScaleFactor": scale, "mobile": False,
        })
        result = driver.execute_cdp_cmd("Page.captureScreenshot", {
            "format": "png", "captureBeyondViewport": True,
            "clip": {"x": 0, "y": y_start, "width": width, "height": chunk_h, "scale": scale},
        })
        img = Image.open(io.BytesIO(base64.b64decode(result["data"]))).convert("RGB")
        screenshots.append(img)
        log(f"  captured: {y_start}-{y_start + chunk_h}px")

    full_img = Image.new(
        "RGB", (screenshots[0].width, sum(i.height for i in screenshots)), "white"
    )
    y_off = 0
    for img in screenshots:
        full_img.paste(img, (0, y_off))
        y_off += img.height
    return full_img


def _load_font(size):
    for path in _FONT_CANDIDATES:
        try:
            return ImageFont.truetype(path, size)
        except OSError:
            continue
    return ImageFont.load_default()


def _fit_text(draw, text, font, max_width):
    if draw.textlength(text, font=font) <= max_width:
        return text
    while text and draw.textlength(text + "…", font=font) > max_width:
        text = text[:-1]
    return text + "…"


def paginate(full_img, title, url, date_str, page_size="a4",
             with_header=True, with_footer=True):
    """Slice the stitched screenshot into pages with header/footer decoration."""
    img_w, img_h = full_img.size
    k = img_w / _REF_WIDTH  # proportional scaling factor

    header_h = round(90 * k) if with_header else 0
    footer_h = round(90 * k) if with_footer else 0
    margin = round(40 * k)

    pw_mm, ph_mm = PAGE_SIZES[page_size]
    page_h = int(img_w * ph_mm / pw_mm)
    content_h = page_h - header_h - footer_h

    font_title = _load_font(round(36 * k))
    font_url = _load_font(round(28 * k))
    font_page = _load_font(round(34 * k))

    total_pages = -(-img_h // content_h)
    pages, page_num, y = [], 0, 0

    while y < img_h:
        page_num += 1
        bottom = min(y + content_h, img_h)
        content = full_img.crop((0, y, img_w, bottom))
        page = Image.new("RGB", (img_w, page_h), "white")
        page.paste(content, (0, header_h))
        draw = ImageDraw.Draw(page)

        if with_header:
            draw.rectangle([(0, 0), (img_w, header_h)], fill="#f5f5f5")
            draw.line([(0, header_h), (img_w, header_h)], fill="#999999", width=max(1, round(3 * k)))
            date_w = draw.textlength(date_str, font=font_title)
            title_text = _fit_text(draw, title, font_title, img_w - date_w - 3 * margin)
            ty = (header_h - round(36 * k)) // 2
            draw.text((margin, ty), title_text, fill="#111111", font=font_title)
            draw.text((img_w - margin - date_w, ty), date_str, fill="#111111", font=font_title)

        if with_footer:
            draw.rectangle([(0, page_h - footer_h), (img_w, page_h)], fill="#f5f5f5")
            draw.line([(0, page_h - footer_h), (img_w, page_h - footer_h)],
                      fill="#999999", width=max(1, round(3 * k)))
            num_text = f"{page_num} / {total_pages}"
            num_w = draw.textlength(num_text, font=font_page)
            url_text = _fit_text(draw, url, font_url, img_w - num_w - 3 * margin)
            draw.text((margin, page_h - footer_h + (footer_h - round(28 * k)) // 2),
                      url_text, fill="#222222", font=font_url)
            draw.text((img_w - margin - num_w, page_h - footer_h + (footer_h - round(34 * k)) // 2),
                      num_text, fill="#111111", font=font_page)

        pages.append(page)
        y += content_h

    return pages


def save_pdf(pages, out_path, page_size="a4"):
    """Save pages as a PDF whose physical size matches the chosen paper size."""
    pw_mm, _ = PAGE_SIZES[page_size]
    dpi = pages[0].width / (pw_mm / 25.4)
    pages[0].save(out_path, "PDF", resolution=dpi, save_all=True, append_images=pages[1:])
